# Jim; Copied this off stack overflow. Not sure about this, does seem to ignore my failing unite tests... Give up!
# Also, I can't get it to run automatically - it can only be triggered from the UI. Shouldn't it run on every commit
# or something?
name: CI pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Build with Maven
        run: mvn --no-transfer-progress -B compile --file pom.xml
